{
  "first_tests.py::TestCalc::test_multiply_calculation_failed": true
}